import { cookies } from "next/headers";
import { db } from "./db";
import { digest } from "./crypto";
import type { Role, User } from "./types";
export class HttpError extends Error {constructor(public status:number,message:string){super(message);}}
export async function currentUser():Promise<User|null>{const token=(await cookies()).get("medsentinel_session")?.value;if(!token)return null;const row=db().prepare("SELECT u.id,u.email,u.name,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>?").get(digest(token),Date.now()) as User|undefined;return row??null;}
export async function requireUser(allowed?:Role[]){const user=await currentUser();if(!user)throw new HttpError(401,"Please sign in to continue.");if(allowed&&!allowed.includes(user.role))throw new HttpError(403,"Your role does not have access to this action.");return user;}
export function sameOrigin(request:Request){const origin=request.headers.get("origin");const expected=process.env.APP_ORIGIN??new URL(request.url).origin;const allowed=new Set([expected]);if(process.env.NODE_ENV!=="production"){allowed.add("http://127.0.0.1:3000");allowed.add("http://localhost:3000");}if(!origin||!allowed.has(origin))throw new HttpError(403,"Request origin is not permitted.");}
export function rateLimit(key:string,limit=60,windowMs=60000){const now=Date.now();const c=db();c.prepare("DELETE FROM rate_limits WHERE resets_at<?").run(now);const row=c.prepare("INSERT INTO rate_limits VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count").get(key,now+windowMs) as {count:number};if(row.count>limit)throw new HttpError(429,"Too many requests. Please try again shortly.");}
export async function jsonBody(request:Request){if(!request.headers.get("content-type")?.includes("application/json"))throw new HttpError(415,"Use application/json.");const reader=request.body?.getReader();if(!reader)throw new HttpError(400,"A JSON body is required.");let size=0;const chunks:Uint8Array[]=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>65536){await reader.cancel();throw new HttpError(413,"Request exceeds the 64 KB limit.");}chunks.push(value);}try{return JSON.parse(Buffer.concat(chunks).toString("utf8"));}catch{throw new HttpError(400,"Invalid JSON.");}}
export function apiError(error:unknown){if(error instanceof HttpError)return Response.json({error:error.message},{status:error.status});if(error instanceof Error&&error.name==="ZodError")return Response.json({error:"The submitted data is invalid."},{status:400});console.error("API failure",error instanceof Error?error.name:"unknown");return Response.json({error:"The request could not be completed."},{status:500});}
